#!/bin/bash


# System installation info
SOURCE_PARENT=/opt/games
SOURCE=${SOURCE_PARENT}/zelda-classic

# Local installation info
LOCAL=${HOME}/.local/share
TARGET=${LOCAL}/zelda-classic

# Remote file info
URL=http://www.zeldaclassic.com/
DLID_LINUX=100
VERSION=2-50-2
ARCHIVE=zc-${VERSION}-linux.tar.gz
REMOTE=${URL}download/${DLID_LINUX}
REMOTE_STATIC=${URL}files/${ARCHIVE}

# Execution info
LAUNCHER=zlaunch-l


if [ "$1" = "download" ]; then
	# Save current directory
	HERE=$(pwd)
	
	# Change to temp directory
	cd /tmp
	
	# Cache binary archive
	if [ ! -f "/tmp/${ARCHIVE}" ]; then
		printf "\nDownloading game binaries "
		echo -e "(v${VERSION}) ..." | sed -e 's/-/./g'
		
		# Download the binary archive
		curl -O "${REMOTE_STATIC}"
	else
		echo -e "\nPreviously cached archive found: /tmp/${ARCHIVE}"
	fi
	
	# Make sure cached archive exists
	if [ ! -f "/tmp/${ARCHIVE}" ]; then
		echo -e "\nERROR: Could not download binary archive"
		exit 1
	fi
	
	# Check for write access & pre-existing binary data files
	if [ ! -w "${SOURCE_PARENT}" ]; then
		echo -e "\nERROR: No write access to \"${SOURCE_PARENT}\""
		exit 1
	elif [ -e "${SOURCE}" ]; then
		read -p "\nFound existing game files, remove? (${SOURCE}) [y/N]: " RMSOURCE
		
		case "${RMSOURCE}" in
			[yY][eE][sS]|[yY])
				rm -vrf "${SOURCE}"
				;;
			*)
				echo "Aborting ..."
				exit 0
				;;
		esac
	fi
	
	# Extract binary files to source directory
	echo "Extracting game files ..."
	
	# Return to previous directory
	cd ${HERE}
	
	# Downloaded & extracted successfully
	exit 0

fi

if [ ! -d "${TARGET}" ]; then
	if [ -d "${SOURCE}" ]; then
		if [ ! -d "${LOCAL}" ]; then
			mkdir -p "${LOCAL}";
		elif [ ! -d "${TARGET}" ]; then
			echo "Copying game to local directory ...";
			cp -vR "${SOURCE}" "${TARGET}";
		fi
	else
		echo "Error: Source directory does not exist: ${SOURCE}";
		echo "Try running this script with super user privileges (sudo) with the command \"download\""
		exit 1;
	fi
fi

if [ ! -x "${TARGET}/${LAUNCHER}" ]; then
	if [ -f "${TARGET}/${LAUNCHER}" ]; then
		chmod +x "${TARGET}/${LAUNCHER}";
	else
		echo "Error: Launcher does not exist: ${TARGET}/${LAUNCHER}";
		exit 1;
	fi
fi

cd "${TARGET}";
./${LAUNCHER} $@;

# FIXME: Backup save data after play
